package mx.edu.tpdm_u2_practica3_15401052

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper

class BaseDatos(
    context: Context,
    name: String,
    factory: SQLiteDatabase.CursorFactory?,
    version: Int
):SQLiteOpenHelper(context, name, factory, version){
    override fun onCreate(p0: SQLiteDatabase?) {
        p0?.execSQL("CREATE TABLE CLIENTE(IDCLIENTE INTEGER PRIMARY KEY AUTOINCREMENT, NOTELEFONO VARCHAR(30), NOMBRE VARCHAR(400), DOMICILIO VARCHAR(400), IDEMPRESA INTEGER, FOREIGN KEY(IDEMPRESA) REFERENCES EMPRESA(IDEMPRESA))")
        p0?.execSQL("CREATE TABLE ALMACEN(IDALMACEN INTEGER PRIMARY KEY AUTOINCREMENT, PRODUCTO VARCHAR(400), CANTIDAD INTEGER, PRECIO FLOAT)")
        p0?.execSQL("CREATE TABLE COMPRA(IDCOMPRA INTEGER PRIMARY KEY AUTOINCREMENT, FECHA DATE, IDCLIENTE INTEGER, TOTAL FLOAT, FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE))")
        p0?.execSQL("CREATE TABLE EMPRESA(IDEMPRESA INTEGER PRIMARY KEY AUTOINCREMENT, DESCRIPCION VARCHAR(400), DOMICILIO VARCHAR(400))")
        p0?.execSQL("CREATE TABLE DETALLECOMPRA(IDDETALLE INTEGER PRIMARY KEY AUTOINCREMENT, IDALMACEN INTEGER, CANTIDAD INTEGER, PRECIO FLOAT, IDCOMPRA INTEGER, FOREIGN KEY(IDALMACEN) REFERENCES ALMACEN(IDALMACEN), FOREIGN KEY(IDCOMPRA) REFERENCES COMPRA(IDCOMPRA))")

    }

    override fun onUpgrade(p0: SQLiteDatabase?, p1: Int, p2: Int) {

    }
}